server {
    server_name muhammadrofiq.my.id portal.muhammadrofiq.my.id localhost;

    tcp_nodelay on;
    tcp_nopush on;
    client_max_body_size 50M;

    location ^~ /uploads/ {
        alias /home/xruncy/repo/uploads/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location ^~ /_next/ {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/muhammadrofiq.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/muhammadrofiq.my.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = portal.muhammadrofiq.my.id) {
        return 301 https://$host$request_uri;
    }

    if ($host = muhammadrofiq.my.id) {
        return 301 https://$host$request_uri;
    }

    listen 80 default_server;
    server_name muhammadrofiq.my.id portal.muhammadrofiq.my.id localhost;
    return 301 https://$host$request_uri;
}
